cameras:
  - id: 1
    port: 8080
    has_fire_detection_enabled: True
  - id: 2
    port: 8010
    has_fire_detection_enabled: False
  - id: 3
    port: 8001
    has_fire_detection_enabled: False
  - id: 4
    port: 8002
    has_fire_detection_enabled: False

is_video_saving_enabled: True
HOST: 0.0.0.0